name: Prisma Migration Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Prisma
        run: npm install -g prisma

      - name: Migrate database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: prisma migrate deploy --schema=./prisma/schema.prisma --preview-feature
